Added resources to be deleted from workflow

diff --git a/.github/workflows/check_old_resources.yml b/.github/workflows/check_old_resources.yml
--- a/.github/workflows/check_old_resources.yml
+++ b/.github/workflows/check_old_resources.yml
@@ -22,7 +22,7 @@ jobs:
         create_credentials_file: true
         workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_ID }}
         service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
-        project_id: 'p-601-np-membership-adt'
+        project_id: 'p-601-np-membership-qat'
 
     - name: Install Terraform
       uses: hashicorp/setup-terraform@v3
@@ -33,7 +33,7 @@ jobs:
         terraform {
           backend "gcs" {
             bucket = "gcp-gcs-cicd-core-mbr-bc-lead"
-            prefix = "adt/bc"
+            prefix = "qat/bc"
           }
         }
         EOF
@@ -41,17 +41,26 @@ jobs:
     - name: Initialize Terraform backend
       run: terraform init -input=false
 
-    # - name: Disable deletion protection via gcloud
-    #   run: |
-    #     gcloud sql instances patch lead-mgmt-adt \
-    #       --no-deletion-protection \
-    #       --project=p-601-np-membership-adt
+    - name: Disable deletion protection via gcloud
+      run: |
+        gcloud sql instances patch lead-mgmt-qat \
+          --no-deletion-protection \
+          --project=p-601-np-membership-qat
+
+    - name: Delete instance via gcloud
+      run: |
+        gcloud sql instances delete lead-mgmt-qat \
+          --quiet \
+          --project=p-601-np-membership-qat
+
+    - name: Remove resource from Terraform state
+      run: terraform state rm module.cloud_sql_instance.google_sql_database_instance.this
+
+    - name: Refresh Terraform state
+      run: terraform refresh -input=false
 
     - name: List resources in remote state
       run: terraform state list
-
-    # - name: Refresh Terraform state
-    #   run: terraform refresh -input=false
 
     # - name: Remove deletion protection and destroy instance
     #   run: |
@@ -81,43 +90,43 @@ jobs:
 
     #     terraform destroy -auto-approve -target=google_sql_database_instance.this
 
-    # - name: Destroy resources one by one
-    #   run: |
-    #     resources=(
-    #       'google_project_service.required_apis_recreate["artifactregistry.googleapis.com"]'
-    #       'google_project_service.required_apis_recreate["cloudfunctions.googleapis.com"]'
-    #       'google_project_service.required_apis_recreate["cloudresourcemanager.googleapis.com"]'
-    #       'google_project_service.required_apis_recreate["cloudscheduler.googleapis.com"]'
-    #       'google_project_service.required_apis_recreate["monitoring.googleapis.com"]'
-    #       'google_project_service.required_apis_recreate["pubsub.googleapis.com"]'
-    #       'google_project_service.required_apis_recreate["secretmanager.googleapis.com"]'
-    #       'google_project_service.required_apis_recreate["servicenetworking.googleapis.com"]'
-    #       'google_project_service.required_apis_recreate["sqladmin.googleapis.com"]'
-    #       'google_project_service.required_apis_recreate["storage.googleapis.com"]'
-    #       google_service_account.my_service_account
-    #       google_storage_bucket.this
-    #       module.cloud_sql_instance.data.google_compute_network.shared_vpc
-    #       module.cloud_sql_instance.data.google_compute_subnetwork.my-subnetwork
-    #       module.cloud_sql_instance.google_sql_database.app_database
-    #       module.cloud_sql_instance.google_sql_database_instance.this
-    #       module.cloud_sql_instance.google_sql_user.iam_service_account_user
-    #       module.cloud_sql_instance.google_sql_user.postgres_admin
-    #       module.cloud_sql_instance.null_resource.postgresql_ready
-    #       module.kubeflow_registry.google_artifact_registry_repository.this
-    #       module.monitoring_alert.google_monitoring_alert_policy.cloud_run_job_failure
-    #       module.monitoring_alert.google_monitoring_notification_channel.lead_mgmt_email
-    #       module.service_now_password.google_secret_manager_secret.this
-    #       module.service_now_password.google_secret_manager_secret_version.this
-    #       module.service_now_username.google_secret_manager_secret.this
-    #       module.service_now_username.google_secret_manager_secret_version.this
-    #       module.snow_sync_scheduler.google_cloud_scheduler_job.snow_sync_scheduler
-    #       module.snow_sync_scheduler.google_pubsub_topic.snow_sync_trigger
-    #     )
+    - name: Destroy resources one by one
+      run: |
+        resources=(
+          'google_project_service.required_apis_recreate["artifactregistry.googleapis.com"]'
+          'google_project_service.required_apis_recreate["cloudfunctions.googleapis.com"]'
+          'google_project_service.required_apis_recreate["cloudresourcemanager.googleapis.com"]'
+          'google_project_service.required_apis_recreate["cloudscheduler.googleapis.com"]'
+          'google_project_service.required_apis_recreate["monitoring.googleapis.com"]'
+          'google_project_service.required_apis_recreate["pubsub.googleapis.com"]'
+          'google_project_service.required_apis_recreate["secretmanager.googleapis.com"]'
+          'google_project_service.required_apis_recreate["servicenetworking.googleapis.com"]'
+          'google_project_service.required_apis_recreate["sqladmin.googleapis.com"]'
+          'google_project_service.required_apis_recreate["storage.googleapis.com"]'
+          google_service_account.my_service_account
+          google_storage_bucket.this
+          module.cloud_sql_instance.data.google_compute_network.shared_vpc
+          module.cloud_sql_instance.data.google_compute_subnetwork.my-subnetwork
+          module.cloud_sql_instance.google_sql_database.app_database
+          module.cloud_sql_instance.google_sql_database_instance.this
+          module.cloud_sql_instance.google_sql_user.iam_service_account_user
+          module.cloud_sql_instance.google_sql_user.postgres_admin
+          module.cloud_sql_instance.null_resource.postgresql_ready
+          module.kubeflow_registry.google_artifact_registry_repository.this
+          module.monitoring_alert.google_monitoring_alert_policy.cloud_run_job_failure
+          module.monitoring_alert.google_monitoring_notification_channel.lead_mgmt_email
+          module.service_now_password.google_secret_manager_secret.this
+          module.service_now_password.google_secret_manager_secret_version.this
+          module.service_now_username.google_secret_manager_secret.this
+          module.service_now_username.google_secret_manager_secret_version.this
+          module.snow_sync_scheduler.google_cloud_scheduler_job.snow_sync_scheduler
+          module.snow_sync_scheduler.google_pubsub_topic.snow_sync_trigger
+        )
 
-    #     for res in "${resources[@]}"; do
-    #       echo "Destroying resource: $res"
-    #       terraform destroy -auto-approve -target="$res" || echo "Failed to destroy $res, continuing..."
-    #     done
+        for res in "${resources[@]}"; do
+          echo "Destroying resource: $res"
+          terraform destroy -auto-approve -target="$res" || echo "Failed to destroy $res, continuing..."
+        done
     - name: Destroy resources one by one
       run: |
         gcloud run jobs delete lead-match-job --region=us-central1 --quiet
